theme: jekyll-theme-minimal
title: Gökhan Buturak
author: Gökhan Buturak
description: Lecturer in Economics at Manchester Metropolitan University. PhD in Economics, Stockholm School of Economics.
author_email: buturak@gmail.com
show_downloads: false
layout: home
