theme: jekyll-theme-minimal
title: Gökhan Buturak
author: Gökhan Buturak
description: Freelance researcher. PhD in Economics, Stockholm School of Economics. Email: buturak@gmail.com

author_email: buturak@gmail.com
show_downloads: false
layout: home
