theme: jekyll-theme-minimal
title: Gökhan Buturak
author: Gökhan Buturak
description: Freelance researcher.  <br />  PhD in Economics, Stockholm School of Economics. <br />  "Email: buturak@gmail.com"
author_email: buturak@gmail.com
show_downloads: false
layout: home
